name = lucasrasmussen
description = A customized Theme designed for my personal website.
screenshot = screenshot.png
engine = phptemplate
core = 7.x

; Styles
stylesheets[all][] = css/lucasrasmussen.normalize.css
stylesheets[all][] = css/lucasrasmussen.hacks.css
stylesheets[all][] = css/lucasrasmussen.styles.css
stylesheets[all][] = css/lucasrasmussen.no-query.css

; Scripts
scripts[] = js/lucasrasmussen.behaviors.js

; Regions
regions[header]         = Header
regions[navigation]     = Navigation
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First Sidebar
regions[sidebar_second] = Second Sidebar
regions[footer]         = Footer
